/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.RegionalManager;

import Business.DisabilityCenter;
import Business.Employee.Employee;
import Business.Enterprise.CenterEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Role.CenterHeadRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cardinal
 */
public class CreateCenterAndCenterHead extends javax.swing.JPanel {

    /**
     * Creates new form CreateCenterAndCenterHead
     */
    private JPanel bottomJPanel;
    private DisabilityCenter disabilityCenter;
    private Network network;
    
    public CreateCenterAndCenterHead(JPanel bottomJPanel, Network network, DisabilityCenter disabilityCenter) {
        initComponents();
        this.bottomJPanel = bottomJPanel;
        this.disabilityCenter = disabilityCenter;
        this.network = network;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtFieldCenterHead = new javax.swing.JTextField();
        txtFieldCenterName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFieldName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFieldPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(192, 159, 128));

        enterpriseJTable.setForeground(new java.awt.Color(118, 50, 63));
        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Center Name", "Center head"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterpriseJTable);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(118, 50, 63));
        jLabel6.setText("Center Name*");

        txtFieldCenterHead.setForeground(new java.awt.Color(118, 50, 63));

        txtFieldCenterName.setForeground(new java.awt.Color(118, 50, 63));
        txtFieldCenterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldCenterNameActionPerformed(evt);
            }
        });
        txtFieldCenterName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldCenterNameKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(118, 50, 63));
        jLabel4.setText("Password*");

        txtFieldName.setForeground(new java.awt.Color(118, 50, 63));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(118, 50, 63));
        jLabel5.setText("Username*");

        txtFieldPassword.setForeground(new java.awt.Color(118, 50, 63));
        txtFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldPasswordActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(118, 50, 63));
        jLabel2.setText("Center Head Name*");

        submitJButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(118, 50, 63));
        submitJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/RegionalManager/icons8_Save_as_32px_1.png"))); // NOI18N
        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        backJButton.setForeground(new java.awt.Color(118, 50, 63));
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/RegionalManager/icons8_Back_To_32px_1.png"))); // NOI18N
        backJButton.setText(" Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(118, 50, 63));
        jLabel8.setText("Create Center and Center Head");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(submitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtFieldCenterName)
                                .addComponent(txtFieldCenterHead, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFieldCenterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFieldCenterHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addComponent(submitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backJButton)
                .addContainerGap(182, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldCenterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldCenterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldCenterNameActionPerformed

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseJTable.getModel();
        model.setRowCount(0);
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise instanceof CenterEnterprise) {
                CenterEnterprise centerEnterprise = (CenterEnterprise) enterprise;
                Object[] row = new Object[model.getColumnCount()];
                row[1] = centerEnterprise.getCenterHead().getName();
                row[0] = enterprise.getName();
                model.addRow(row);
            }
        }
    }
    
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        bottomJPanel.remove(this);
        Component[] componentArray = bottomJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        RegionalManagerWorkAreaJPanel regionalManagerWorkAreaJPanel = (RegionalManagerWorkAreaJPanel) component;

        CardLayout layout = (CardLayout) bottomJPanel.getLayout();
        layout.previous(bottomJPanel);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        String centerName = txtFieldCenterName.getText();
        String centerhead = txtFieldCenterHead.getText();
        String username = txtFieldName.getText();
        String password = String.valueOf(txtFieldPassword.getPassword());
        
        if(txtFieldCenterName.getText().isEmpty() || txtFieldCenterHead.getText().isEmpty()){
            java.util.logging.Logger.getLogger(CreateCenterAndCenterHead.class.getName()).log(java.util.logging.Level.INFO, "Please enter Center and Center Head Name");
            JOptionPane.showMessageDialog(null, "Please enter Center and Center Head Name");
            return;
        }
        if(txtFieldName.getText().length() < 5 || txtFieldPassword.getText().length() < 5){
            JOptionPane.showMessageDialog(null, "Please enter username and password with length more than 5 characters");
            java.util.logging.Logger.getLogger(CreateCenterAndCenterHead.class.getName()).log(java.util.logging.Level.INFO, "Please enter Center and Center Head Name");
            return;
        }
        
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise instanceof CenterEnterprise) {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (organization.getName().equals(centerName)) {
                        JOptionPane.showMessageDialog(null, "Center Name already exists.Please create with different name");
                        java.util.logging.Logger.getLogger(CreateCenterAndCenterHead.class.getName()).log(java.util.logging.Level.INFO, "Center Name "+centerName+" already exists.Please create with different name");
                        txtFieldCenterName.setText("");
                        return;
                    }
                }
            }
        }
                
        CenterEnterprise centerEnterprise = (CenterEnterprise) network.getEnterpriseDirectory().createCenter(centerName);

        Employee employee = centerEnterprise.getEmployeeDirectory().createEmployee(centerhead);

        UserAccount account = centerEnterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new CenterHeadRole());
        
        if(account == null){
            //error occured while creating user account
            network.getEnterpriseDirectory().removeCenter(centerEnterprise);
            return;
        }
        
        centerEnterprise.addCenterHead(centerhead);
        JOptionPane.showMessageDialog(null, "Center has been created and center head has been appointed");
        java.util.logging.Logger.getLogger(CreateCenterAndCenterHead.class.getName()).log(java.util.logging.Level.INFO, "Center "+centerName+" has been created and center head "+centerhead+" has been appointed!");
        populateTable();
        txtFieldCenterName.setText("");
        txtFieldCenterHead.setText("");
        txtFieldName.setText("");
        txtFieldPassword.setText("");
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void txtFieldCenterNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldCenterNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldCenterNameKeyPressed

    private void txtFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTable enterpriseJTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField txtFieldCenterHead;
    private javax.swing.JTextField txtFieldCenterName;
    private javax.swing.JTextField txtFieldName;
    private javax.swing.JPasswordField txtFieldPassword;
    // End of variables declaration//GEN-END:variables
}
