/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.RegionalManager;

import Business.DisabilityCenter;
import Business.Network.Network;
import Business.UserAccount.UserAccount;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author cardinal
 */

public class RegionalManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegionalManagerWorkAreaJPanel
     */
    private JPanel bottomJPanel;
    private DisabilityCenter disabilityCenter;
    private UserAccount account;
    //Enterprise enterprise;
    private Network network;
    
    public RegionalManagerWorkAreaJPanel(JPanel bottomPanel, Network network, UserAccount account, DisabilityCenter disabilityCenter) {
        initComponents();
       this.bottomJPanel= bottomPanel;
       this.disabilityCenter = disabilityCenter;
       this.account = account;
       this.network = network;
       valueLabel.setText(account.getEmployee().getName());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        btnViewBudgetReportOfCenters = new javax.swing.JButton();
        btnCreateCenter = new javax.swing.JButton();
        btnAddSupplier = new javax.swing.JButton();
        btnCenterBudget = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(192, 159, 128));

        enterpriseLabel.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(118, 50, 63));
        enterpriseLabel.setText("Regional Manager :");

        valueLabel.setFont(new java.awt.Font("Felix Titling", 1, 30)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(118, 50, 63));
        valueLabel.setText("<value>");

        btnViewBudgetReportOfCenters.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnViewBudgetReportOfCenters.setForeground(new java.awt.Color(118, 50, 63));
        btnViewBudgetReportOfCenters.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/RegionalManager/icons8_Bar_Chart_32px_6.png"))); // NOI18N
        btnViewBudgetReportOfCenters.setText("View Budget Report of Centers");
        btnViewBudgetReportOfCenters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBudgetReportOfCentersActionPerformed(evt);
            }
        });

        btnCreateCenter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCreateCenter.setForeground(new java.awt.Color(118, 50, 63));
        btnCreateCenter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/RegionalManager/icons8_Hospital_3_32px_1.png"))); // NOI18N
        btnCreateCenter.setText("Create Center");
        btnCreateCenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCenterActionPerformed(evt);
            }
        });

        btnAddSupplier.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddSupplier.setForeground(new java.awt.Color(118, 50, 63));
        btnAddSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/RegionalManager/icons8_Person_32px.png"))); // NOI18N
        btnAddSupplier.setText("Add Supplier");
        btnAddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSupplierActionPerformed(evt);
            }
        });

        btnCenterBudget.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCenterBudget.setForeground(new java.awt.Color(118, 50, 63));
        btnCenterBudget.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/RegionalManager/icons8_Money_Bag_32px_1.png"))); // NOI18N
        btnCenterBudget.setText("Set Center Budget");
        btnCenterBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCenterBudgetActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(118, 50, 63));
        jLabel6.setText("Regional Manage Role Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(enterpriseLabel)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAddSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnViewBudgetReportOfCenters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCreateCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCenterBudget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel))
                .addGap(37, 37, 37)
                .addComponent(btnCreateCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnViewBudgetReportOfCenters, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnAddSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCenterBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewBudgetReportOfCentersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBudgetReportOfCentersActionPerformed
       BudgetReportsJPanel budgetReportsJPanel = new BudgetReportsJPanel(bottomJPanel, network);
        bottomJPanel.add("budgetReportsJPanel",budgetReportsJPanel);
        CardLayout layout=(CardLayout)bottomJPanel.getLayout();
        layout.next(bottomJPanel);

    }//GEN-LAST:event_btnViewBudgetReportOfCentersActionPerformed

    private void btnCreateCenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCenterActionPerformed
        CreateCenterAndCenterHead createCenterAndCenterHead = new CreateCenterAndCenterHead(bottomJPanel, network, disabilityCenter);
        bottomJPanel.add("createCenterAndCenterHead",createCenterAndCenterHead);
        CardLayout layout=(CardLayout)bottomJPanel.getLayout();
        layout.next(bottomJPanel);
    }//GEN-LAST:event_btnCreateCenterActionPerformed

    private void btnAddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupplierActionPerformed
        // TODO add your handling code here:
        AddSupplierJPanel addSupplierJPanel = new AddSupplierJPanel(bottomJPanel, disabilityCenter);
        bottomJPanel.add("addSupplierJPanel",addSupplierJPanel);
        CardLayout layout=(CardLayout)bottomJPanel.getLayout();
        layout.next(bottomJPanel);
    }//GEN-LAST:event_btnAddSupplierActionPerformed

    private void btnCenterBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCenterBudgetActionPerformed
        //null pointer
        SetCenterBudgetJPanel setCenterBudgetJPanel = new SetCenterBudgetJPanel(bottomJPanel, network, disabilityCenter);
        bottomJPanel.add("SetCenterBudgetJPanel",setCenterBudgetJPanel);
        CardLayout layout=(CardLayout)bottomJPanel.getLayout();
        layout.next(bottomJPanel);
    }//GEN-LAST:event_btnCenterBudgetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSupplier;
    private javax.swing.JButton btnCenterBudget;
    private javax.swing.JButton btnCreateCenter;
    private javax.swing.JButton btnViewBudgetReportOfCenters;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
