/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.RegionalManager;

import Business.DB4OUtil.DB4OUtil;
import Business.DisabilityCenter;
import Business.Enterprise.CenterEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sharv
 */
public class SetCenterBudgetJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SetCenterBudgetJPanel
     */
    private JPanel bottomJPanel;
    private DisabilityCenter disabilityCenter;
    private Network network;

    public SetCenterBudgetJPanel(JPanel bottomJPanel, Network network, DisabilityCenter disabilityCenter) {
        initComponents();
        this.bottomJPanel = bottomJPanel;
        this.disabilityCenter = disabilityCenter;
        this.network = network;
        lblNetwork.setText(this.network.getName());
        lblBudget.setText(String.valueOf(network.getBudget()));
        populateCenterComboBox();
        populateTable();
    }

    public void populateCenterComboBox() {
        centerJCombo.removeAllItems();
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise instanceof CenterEnterprise) {
                centerJCombo.addItem(enterprise);
            }
        }
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblCenterBudget.getModel();
        model.setRowCount(0);
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise instanceof CenterEnterprise) {
                CenterEnterprise centerEnterprise = (CenterEnterprise) enterprise;
                Object[] row = new Object[model.getColumnCount()];
                row[1] = centerEnterprise.getCenterBudget();
                row[0] = enterprise;
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        lblNetwork = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        lblBudget = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCenterBudget = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        centerJCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtCenterBudget = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnCenterBudget = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Create Center and Center Head");

        setBackground(new java.awt.Color(192, 159, 128));

        enterpriseLabel.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        enterpriseLabel.setText("Network:");

        lblNetwork.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        lblNetwork.setText("<value>");

        enterpriseLabel1.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        enterpriseLabel1.setText("Budget:");

        lblBudget.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        lblBudget.setText("<value>");

        tblCenterBudget.setForeground(new java.awt.Color(118, 50, 63));
        tblCenterBudget.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Center Name", "Budget Assigned"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCenterBudget);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(118, 50, 63));
        jLabel1.setText("Center Name: ");

        centerJCombo.setForeground(new java.awt.Color(118, 50, 63));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(118, 50, 63));
        jLabel2.setText("Set Budget: ");

        txtCenterBudget.setForeground(new java.awt.Color(118, 50, 63));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(118, 50, 63));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/RegionalManager/icons8_Back_To_32px_1.png"))); // NOI18N
        btnBack.setText(" Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCenterBudget.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCenterBudget.setForeground(new java.awt.Color(118, 50, 63));
        btnCenterBudget.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/RegionalManager/icons8_Money_Bag_32px_1.png"))); // NOI18N
        btnCenterBudget.setText("Set Budget");
        btnCenterBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCenterBudgetActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(118, 50, 63));
        jLabel5.setText("Set Center Budget");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCenterBudget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(centerJCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCenterBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnBack)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(lblNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(192, 192, 192)
                                .addComponent(enterpriseLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNetwork)
                    .addComponent(enterpriseLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBudget))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(centerJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCenterBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btnCenterBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnBack)
                .addContainerGap(156, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        bottomJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) bottomJPanel.getLayout();
        cardLayout.previous(bottomJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCenterBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCenterBudgetActionPerformed
        //double budg = 0.0;
        double budget = 0.0;
        double centerBudget = 0.0;
        Enterprise enterprise = (Enterprise) centerJCombo.getSelectedItem();
        try {
             budget = Double.parseDouble(txtCenterBudget.getText());
            if(budget <= 0){
                JOptionPane.showMessageDialog(null, "Value needs to be greater than 0");
                java.util.logging.Logger.getLogger(SetCenterBudgetJPanel.class.getName()).log(java.util.logging.Level.INFO, "Value needs to be greater than 0");
                return;
            }
             //budg = ((CenterEnterprise)enterprise).getCenterBudget();
             centerBudget = ((CenterEnterprise)enterprise).getCenterBudget();
            if (network.getBudget() - budget >= 0) {
                network.setBudget(network.getBudget() - budget);
                ((CenterEnterprise)enterprise).setCenterBudget(centerBudget+budget);
                txtCenterBudget.setText("");
                JOptionPane.showMessageDialog(null, "Center Budget has been set.");
                java.util.logging.Logger.getLogger(SetCenterBudgetJPanel.class.getName()).log(java.util.logging.Level.INFO, "Center Budget has been set to "+((CenterEnterprise)enterprise).getCenterBudget());
            } else {
                JOptionPane.showMessageDialog(this, "Please select budget less than Network Budget");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please add numeric field for Budget");
            txtCenterBudget.setText("");
            return;
        }
        lblBudget.setText(String.valueOf(network.getBudget()));
        //populateCenterBudgetTable(enterprise);
        
        populateTable();
        DB4OUtil.getInstance().storeSystem(disabilityCenter);
    }//GEN-LAST:event_btnCenterBudgetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCenterBudget;
    private javax.swing.JComboBox centerJCombo;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBudget;
    private javax.swing.JLabel lblNetwork;
    private javax.swing.JTable tblCenterBudget;
    private javax.swing.JTextField txtCenterBudget;
    // End of variables declaration//GEN-END:variables
}
