package UserInterface;

import Business.DB4OUtil.DB4OUtil;
import Business.DisabilityCenter;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountManager;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.logging.LogManager;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author cardinal
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private DisabilityCenter disabilityCenter;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    final static Logger logger = Logger.getLogger(MainJFrame.class.getName());

    public MainJFrame() {
        initComponents();

        try {
            LogManager.getLogManager().readConfiguration(new FileInputStream("logging.properties"));
        } catch (SecurityException | IOException e1) {
            e1.printStackTrace();
        }

        disabilityCenter = dB4OUtil.retrieveSystem();
        UserAccountManager.initializeAllUsers(disabilityCenter);
        this.setSize(1680, 1050);
    }

    public void saveDB4O() {
        dB4OUtil.storeSystem(disabilityCenter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFieldusername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFieldPassword = new javax.swing.JPasswordField();
        logoutJButton = new javax.swing.JButton();
        loginJButton2 = new javax.swing.JButton();
        bottomJPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(new java.awt.Color(118, 50, 63));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(215, 206, 199));
        jLabel1.setText("User Name");

        txtFieldusername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtFieldusername.setForeground(new java.awt.Color(118, 50, 63));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(215, 206, 199));
        jLabel2.setText("Password");

        txtFieldPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtFieldPassword.setForeground(new java.awt.Color(118, 50, 63));

        logoutJButton.setBackground(new java.awt.Color(215, 206, 199));
        logoutJButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        logoutJButton.setForeground(new java.awt.Color(118, 50, 63));
        logoutJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/iconfinder_logout_account_exit_door_3005766.png"))); // NOI18N
        logoutJButton.setText("Logout");
        logoutJButton.setEnabled(false);
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });

        loginJButton2.setBackground(new java.awt.Color(215, 206, 199));
        loginJButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        loginJButton2.setForeground(new java.awt.Color(118, 50, 63));
        loginJButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/iconfinder_login_account_enter_door_3005767.png"))); // NOI18N
        loginJButton2.setText("Login");
        loginJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtFieldusername, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, Short.MAX_VALUE)
                .addComponent(loginJButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158)
                .addComponent(logoutJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(297, 297, 297))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginJButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtFieldusername, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(txtFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel1);

        bottomJPanel.setBackground(new java.awt.Color(215, 206, 199));
        bottomJPanel.setLayout(new java.awt.CardLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\sharv\\OneDrive\\Desktop\\CenterforDisabilityServicesLogo.jpg.jpeg")); // NOI18N
        jLabel4.setAlignmentX(0.5F);
        jLabel4.setMaximumSize(new java.awt.Dimension(1200, 600));
        jLabel4.setMinimumSize(new java.awt.Dimension(1200, 600));
        jLabel4.setPreferredSize(new java.awt.Dimension(1200, 600));
        bottomJPanel.add(jLabel4, "card2");

        jSplitPane1.setRightComponent(bottomJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
        logoutJButton.setEnabled(false);
        loginJButton2.setEnabled(true);
        txtFieldusername.setEnabled(true);
        txtFieldPassword.setEnabled(true);

        txtFieldusername.setText("");
        txtFieldPassword.setText("");

        bottomJPanel.removeAll();
        JPanel blankJP = new JPanel();
        bottomJPanel.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) bottomJPanel.getLayout();
        crdLyt.next(bottomJPanel);
        dB4OUtil.storeSystem(disabilityCenter);
    }//GEN-LAST:event_logoutJButtonActionPerformed

    private void loginJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButton2ActionPerformed
        // Get user name
        String userName = txtFieldusername.getText();
        // Get Password
        char[] passwordCharArray = txtFieldPassword.getPassword();
        String password = String.valueOf(passwordCharArray);

        //Step1: Check in the system admin user account directory if you have the user
        UserAccount userAccount = disabilityCenter.getUserAccountDirectory().authenticateUser(userName, password);

        Enterprise inEnterprise = null;
        Organization inOrganization = null;
        Network inNetwork = null;
        if (userAccount == null) {
            //Step 2: Go inside each network and check each enterprise
            for (Network network : disabilityCenter.getNetworkList()) {
                //Step 2.a: check against each enterprise
                userAccount = network.getUserAccountDirectory().authenticateUser(userName, password);
                if (userAccount == null) {
                    for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                        userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                        if (userAccount == null) {
                            //Step 3:check against each organization for each enterprise
                            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                                userAccount = organization.getUserAccountDirectory().authenticateUser(userName, password);
                                if (userAccount != null) {
                                    inNetwork = network;
                                    inEnterprise = enterprise;
                                    inOrganization = organization;
                                    break;
                                }
                            }

                        } else {
                            inEnterprise = enterprise;
                            break;
                        }
                        if (inOrganization != null) {
                            break;
                        }
                    }
                    if (inEnterprise != null) {
                        break;
                    }

                }
                if (userAccount != null && inOrganization == null) {
                    inNetwork = network;
                    inOrganization = network;
                    break;
                }
            }

        }

        if (userAccount == null) {
            JOptionPane.showMessageDialog(null, "Invalid credentials");
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.INFO, "Login with Invalid Credentials! Username: "+userName+" Password: "+password);
            txtFieldPassword.setText("");
            txtFieldusername.setText("");
            return;
        } else {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.INFO, "Login Successful! Username: "+userName+" Password: "+password);
            CardLayout layout = (CardLayout) bottomJPanel.getLayout();
            bottomJPanel.add("workArea", userAccount.getRole().createWorkArea(bottomJPanel, userAccount, inOrganization, inEnterprise, disabilityCenter));
            layout.next(bottomJPanel);
        }

        logoutJButton.setEnabled(true);
        loginJButton2.setEnabled(false);
        txtFieldusername.setEnabled(false);
        txtFieldPassword.setEnabled(false);
    }//GEN-LAST:event_loginJButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        logger.info("Closing Window instance");
        dB4OUtil.storeSystem(disabilityCenter);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
                logger.info("New Instance started.");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginJButton2;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JPasswordField txtFieldPassword;
    private javax.swing.JTextField txtFieldusername;
    // End of variables declaration//GEN-END:variables
}
