/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Receptionist;

import Business.DisabilityCenter;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PatientEnterprise;
import Business.Network.Network;
import Business.Organization.Patient;
import Business.UserAccount.UserAccount;
import EmailConfiguration.EmailConfig;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author tejas
 */
public class NewPatientRegistration extends javax.swing.JPanel {

    private JPanel bottomJPanel;
    private Enterprise enterprise;
    private DisabilityCenter business;
    private UserAccount userAccount;
    private Patient newPatient;

    /**
     * Creates new form NewPatientRegistration
     */
    public NewPatientRegistration(JPanel bottomJPanel, Enterprise enterprise, DisabilityCenter business, UserAccount userAccount) {
        initComponents();

        this.bottomJPanel = bottomJPanel;
        this.enterprise = enterprise;
        this.business = business;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPatientEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtContactNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(192, 159, 128));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(118, 50, 63));
        jLabel2.setText("Name:*");

        txtPatientName.setForeground(new java.awt.Color(118, 50, 63));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(118, 50, 63));
        jLabel3.setText("Email:*");

        txtPatientEmail.setForeground(new java.awt.Color(118, 50, 63));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(118, 50, 63));
        jLabel4.setText("Contact Number:*");

        txtContactNumber.setForeground(new java.awt.Color(118, 50, 63));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(118, 50, 63));
        jLabel5.setText("Address:");

        txtAddress.setForeground(new java.awt.Color(118, 50, 63));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnBack.setForeground(new java.awt.Color(118, 50, 63));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Receptionist/icons8_Back_To_32px_1.png"))); // NOI18N
        btnBack.setText(" Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(118, 50, 63));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Receptionist/icons8_Save_as_32px_1.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(118, 50, 63));
        jLabel7.setText("New Patient Registration");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPatientEmail)
                            .addComponent(txtPatientName)
                            .addComponent(txtContactNumber)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel7)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        bottomJPanel.remove(this);
        Component[] componentArray = bottomJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CheckinPatientJPanel checkinJPanel = (CheckinPatientJPanel) component;
        checkinJPanel.setPatientDetailsOnScreen(newPatient);
        CardLayout layout = (CardLayout) bottomJPanel.getLayout();
        layout.previous(bottomJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            String patientName = txtPatientName.getText();
            String patientEmail = txtPatientEmail.getText();
            String patientNumber = txtContactNumber.getText();
            String patientAddress = txtAddress.getText();
            if (txtPatientName.getText().isEmpty() || txtPatientEmail.getText().isEmpty() || txtContactNumber.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter all the mandatory fields");
                return;
            }
            try {
            Integer.parseInt(txtContactNumber.getText());
            } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please add integer for Contatc Number");
            txtContactNumber.setText("");
            return;
            }
            try{
            if(txtContactNumber.getText().length() < 10){
                Integer.parseInt(txtContactNumber.getText());
            }
            }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please add 10 digits for Contact Number");
            txtContactNumber.setText("");
            return;
            }
            
            //Get the PatientEnterprise
            ArrayList<Enterprise> currentEnterpriseList = null;
            PatientEnterprise patientEnterprise = null;
            //Step 1: Get current Network's enterprise list
            for (Network n : business.getNetworkList()) {
                for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                    if (this.enterprise.equals(e)) {
                        currentEnterpriseList = n.getEnterpriseDirectory().getEnterpriseList();
                        break;
                    }
                }
            }
            //Step 2: get Patient Organization List from current Enterprise List
            if (currentEnterpriseList != null) {
                for (Enterprise e : currentEnterpriseList) {
                    if (e instanceof PatientEnterprise) {
                        patientEnterprise = (PatientEnterprise) e;
                        break;
                    }
                }
            }
            
            //Add the new Patient
            Patient newPatient = patientEnterprise.addPatient();
            newPatient.setPatientName(patientName);
            if (emailMatches(patientEmail)) {

                    newPatient.setPatientEmail(patientEmail);
                } else {
                    JOptionPane.showMessageDialog(null, "Email is not valid. Please enter a valid email id!");
                    txtPatientEmail.setText("");
                    return;
                }
            
            newPatient.setPatientNumber(patientNumber);
            newPatient.setPatientAddress(patientAddress);
            
            EmailConfig emailConfig = new EmailConfig();
            Properties smtpProperties = emailConfig.loadProperties();
            emailConfig.sendEmail(smtpProperties, newPatient.getPatientEmail(), "Registration successful", "You have been registered successfully");
            JOptionPane.showMessageDialog(null, "Patient saved successfully!\nPatient ID: " + newPatient.getPatientID());
            java.util.logging.Logger.getLogger(NewPatientRegistration.class.getName()).log(java.util.logging.Level.INFO, "Patient saved successfully!\nPatient ID: " + newPatient.getPatientID());
            //Clear the input fields
            txtPatientName.setText("");
            txtPatientEmail.setText("");
            txtContactNumber.setText("");
            txtAddress.setText("");
            this.newPatient = newPatient;
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(NewPatientRegistration.class.getName()).log(java.util.logging.Level.INFO, "IO Exception" + ex.getMessage());
            System.out.println("IO Exception" + ex.getMessage());
        } catch (MessagingException ex) {
            System.out.println("Messaging Exception" + ex.getMessage());
            java.util.logging.Logger.getLogger(NewPatientRegistration.class.getName()).log(java.util.logging.Level.INFO, "Messaging Exception" + ex.getMessage());
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private boolean emailMatches(String email) {
        if (!email.matches("^[A-Za-z0-9][A-Za-z0-9_]*@[A-Za-z0-9.-]+[\\.[A-Za-z]{2,6}]{1,2}$")) {

            return false;
        }
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtPatientEmail;
    private javax.swing.JTextField txtPatientName;
    // End of variables declaration//GEN-END:variables
}
