/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Receptionist;

import Business.DisabilityCenter;
import Business.Employee.Employee;
import Business.Enterprise.CenterEnterprise;
import Business.Enterprise.Enterprise;
import Business.Organization.Doctor;
import Business.Organization.Nurse;
import Business.Organization.Organization;
import Business.Organization.Patient;
import Business.Organization.Receptionist;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AppointmentWorkRequest;
import Business.WorkQueue.PatientWaitRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cardinal
 */
public class ReceptionistWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel bottomJPanel;
    private Receptionist organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private DisabilityCenter business;

    /**
     * Creates new form ReciptionistWorkAreaJPanel
     */
    public ReceptionistWorkAreaJPanel(JPanel bottomJPanel, UserAccount account, Receptionist organization, Enterprise enterprise, DisabilityCenter business) {
        initComponents();

        this.bottomJPanel = bottomJPanel;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        valueLabel.setText(account.getEmployee().getName());

        refreshPatientQueue();

    }

    public void refreshPatientQueue() {
        DefaultTableModel model = (DefaultTableModel) tblPatientQueue.getModel();
        model.setRowCount(0);

        for (WorkRequest w : userAccount.getWorkQueue().getWorkRequestList()) {
            PatientWaitRequest wr = (PatientWaitRequest) w;
            Patient patient = (Patient) w.getObject();
            Object row[] = new Object[5];
            row[0] = patient.getPatientID();
            row[1] = patient;
            row[2] = w.getStatus();
            row[3] = (wr.getAssignedEmployee() == null) ? "Waiting" : wr.getAssignedEmployee();
            row[4] = wr.getDisabilityType();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCheckinPatient = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatientQueue = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnRefreshQueue = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(192, 159, 128));

        btnCheckinPatient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCheckinPatient.setForeground(new java.awt.Color(118, 50, 63));
        btnCheckinPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Receptionist/icons8_In_Progress_32px_2.png"))); // NOI18N
        btnCheckinPatient.setText("Checkin Patient");
        btnCheckinPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckinPatientActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(118, 50, 63));
        enterpriseLabel.setText("Receptionist :");

        valueLabel.setFont(new java.awt.Font("Felix Titling", 1, 30)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(118, 50, 63));
        valueLabel.setText("<value>");

        tblPatientQueue.setForeground(new java.awt.Color(118, 50, 63));
        tblPatientQueue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "Patient Name", "Status", "Assigned Doctor / Nurse", "Disability Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPatientQueue);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(118, 50, 63));
        jLabel2.setText("Patient Wait Queue");

        btnRefreshQueue.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnRefreshQueue.setForeground(new java.awt.Color(118, 50, 63));
        btnRefreshQueue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Receptionist/icons8_Refresh_32px_1.png"))); // NOI18N
        btnRefreshQueue.setText("Refresh Queue");
        btnRefreshQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshQueueActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(118, 50, 63));
        jLabel7.setText("Receptionist Role Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(btnCheckinPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRefreshQueue))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel))
                .addGap(18, 18, 18)
                .addComponent(btnCheckinPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefreshQueue)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckinPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckinPatientActionPerformed
        CardLayout layout = (CardLayout) bottomJPanel.getLayout();
        bottomJPanel.add(new CheckinPatientJPanel(bottomJPanel, enterprise, business, userAccount));
        layout.next(bottomJPanel);
    }//GEN-LAST:event_btnCheckinPatientActionPerformed

    private void btnRefreshQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshQueueActionPerformed
        refreshPatientQueue();
    }//GEN-LAST:event_btnRefreshQueueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckinPatient;
    private javax.swing.JButton btnRefreshQueue;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPatientQueue;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
