/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Common.PatientHistory;

import Business.DisabilityCenter;
import Business.Enterprise.Patient.PatientHistory;
import Business.Organization.Organization;
import Business.Organization.Patient;
import Business.UserAccount.UserAccount;
import UserInterface.Common.DiagnosePatientJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tejas
 */
public class PatientInfoJPanel extends javax.swing.JPanel {

    private JPanel bottomPanel;
    private UserAccount userAccount;
    private Organization organization;
    private Patient patient;
    private DisabilityCenter business;
    /**
     * Creates new form PatientHistoryJPanel
     */
    public PatientInfoJPanel(JPanel bottomPanel,
                             UserAccount userAccount,
                             Organization organization,
                             Patient patient,
                             DisabilityCenter business) {
        initComponents();
        
        this.bottomPanel = bottomPanel;
        this.userAccount = userAccount;
        this.organization = organization;
        this.patient = patient;
        this.business = business;
        
        populateTable();
    }
    
    public void populateTable(){
        this.txtPatientName.setText(patient.getPatientName());
        this.txtPatientId.setText(String.valueOf(patient.getOrganizationID()));
        
        DefaultTableModel model = (DefaultTableModel) patientHistoryJTable.getModel();

        model.setRowCount(0);
        for (PatientHistory ph : patient.getPatientHistory()) {
            Object row[] = new Object[5];
            row[0] = ph.getPatientHistoryId();
            row[1] = ph.getDateTime();
            row[2] = ph.getDiagnosis();
            row[3] = ph.getDoctor();
            row[4] = ph.getNurse();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientHistoryJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPatientId = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnEditHistory = new javax.swing.JButton();

        setBackground(new java.awt.Color(192, 159, 128));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(118, 50, 63));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient History");

        patientHistoryJTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        patientHistoryJTable.setForeground(new java.awt.Color(118, 50, 63));
        patientHistoryJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date Time", "Diagnosis", "Doctor", "Nurse"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(patientHistoryJTable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(118, 50, 63));
        jLabel2.setText("Patient Name:");

        txtPatientName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtPatientName.setText(" ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(118, 50, 63));
        jLabel3.setText("Patient Id:");

        txtPatientId.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtPatientId.setText(" ");

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(118, 50, 63));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Common/PatientHistory/icons8_Back_To_32px_1.png"))); // NOI18N
        btnBack.setText(" Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnEditHistory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEditHistory.setForeground(new java.awt.Color(118, 50, 63));
        btnEditHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Common/PatientHistory/icons8_Activity_History_32px.png"))); // NOI18N
        btnEditHistory.setText("Edit History");
        btnEditHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(329, 329, 329)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnEditHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtPatientId)
                    .addComponent(txtPatientName))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditHistory)
                .addGap(39, 39, 39)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        bottomPanel.remove(this);
        CardLayout layout = (CardLayout)bottomPanel.getLayout();
        layout.previous(bottomPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEditHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditHistoryActionPerformed
        int row = patientHistoryJTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please make a selection!!");
            return;
        }
        int patientHistoryID = (Integer)patientHistoryJTable.getValueAt(row, 0);
        PatientHistory patientHistory = patient.getPatientHistory().get(patientHistoryID - 1);
        DiagnosePatientJPanel diagnosePatientJPanel = new DiagnosePatientJPanel(bottomPanel, userAccount, organization, patient, business, patientHistory);
        CardLayout cardLayout = (CardLayout) bottomPanel.getLayout();
        bottomPanel.add(diagnosePatientJPanel);
        cardLayout.next(bottomPanel);
    }//GEN-LAST:event_btnEditHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEditHistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable patientHistoryJTable;
    private javax.swing.JLabel txtPatientId;
    private javax.swing.JLabel txtPatientName;
    // End of variables declaration//GEN-END:variables
}
