/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Doctor;

import Business.DisabilityCenter;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.Common.CheckInCheckOutJPanel;
import UserInterface.Common.PatientHistory.AllPatientHistoryJPanel;
import UserInterface.Common.PatientQueueJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author cardinal
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel bottomPanel;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Organization organization;
    private DisabilityCenter business;

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public DoctorWorkAreaJPanel(JPanel bottomPanel, UserAccount userAccount, Organization organization, Enterprise enterprise, DisabilityCenter business) {
        initComponents();
        this.bottomPanel = bottomPanel;
        this.userAccount = userAccount;
        this.organization = organization;
        this.business = business;
        this.enterprise = enterprise;
        
        this.lblWelcomeText.setText("Welcome, " + this.userAccount.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDiagnosePatient = new javax.swing.JButton();
        lblWelcomeText = new javax.swing.JLabel();
        btnPatientHistory = new javax.swing.JButton();
        btnCheckInCheckOut = new javax.swing.JButton();

        setBackground(new java.awt.Color(192, 159, 128));

        btnDiagnosePatient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDiagnosePatient.setForeground(new java.awt.Color(118, 50, 63));
        btnDiagnosePatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Doctor/icons8_Heart_Health_32px.png"))); // NOI18N
        btnDiagnosePatient.setText("Diagnose Patients");
        btnDiagnosePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagnosePatientActionPerformed(evt);
            }
        });

        lblWelcomeText.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        lblWelcomeText.setForeground(new java.awt.Color(118, 50, 63));
        lblWelcomeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeText.setText("Welcome!!");

        btnPatientHistory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPatientHistory.setForeground(new java.awt.Color(118, 50, 63));
        btnPatientHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Doctor/icons8_Activity_History_32px.png"))); // NOI18N
        btnPatientHistory.setText("View Patient History");
        btnPatientHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientHistoryActionPerformed(evt);
            }
        });

        btnCheckInCheckOut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCheckInCheckOut.setForeground(new java.awt.Color(118, 50, 63));
        btnCheckInCheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Doctor/icons8_In_Progress_32px.png"))); // NOI18N
        btnCheckInCheckOut.setText("Shift Check-In / Check-Out");
        btnCheckInCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInCheckOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPatientHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCheckInCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDiagnosePatient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(lblWelcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcomeText)
                .addGap(94, 94, 94)
                .addComponent(btnCheckInCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnDiagnosePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnPatientHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDiagnosePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnosePatientActionPerformed
        
        CardLayout layout = (CardLayout)bottomPanel.getLayout();
        bottomPanel.add("PatientQueueJPanel", new PatientQueueJPanel(bottomPanel, userAccount, organization, business));
        layout.next(bottomPanel);
    }//GEN-LAST:event_btnDiagnosePatientActionPerformed

    private void btnPatientHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientHistoryActionPerformed
        CardLayout layout = (CardLayout)bottomPanel.getLayout();
        bottomPanel.add("AllPatientHistoryJPanel", new AllPatientHistoryJPanel(bottomPanel, enterprise, organization, business, userAccount));
        layout.next(bottomPanel);
    }//GEN-LAST:event_btnPatientHistoryActionPerformed

    private void btnCheckInCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInCheckOutActionPerformed
        CardLayout layout = (CardLayout)bottomPanel.getLayout();
        bottomPanel.add("CheckInCheckOutJPanel", new CheckInCheckOutJPanel(bottomPanel, userAccount, organization, business));
        layout.next(bottomPanel);
    }//GEN-LAST:event_btnCheckInCheckOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckInCheckOut;
    private javax.swing.JButton btnDiagnosePatient;
    private javax.swing.JButton btnPatientHistory;
    private javax.swing.JLabel lblWelcomeText;
    // End of variables declaration//GEN-END:variables
}
