/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Nurse;

import Business.DisabilityCenter;
import Business.Enterprise.Enterprise;
import Business.Organization.Nurse;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.Common.CheckInCheckOutJPanel;
import UserInterface.Common.PatientQueueJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author cardinal
 */
public class NurseWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NurseWorkAreaJPanel
     */
    private JPanel bottomPanel;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Organization organization;
    private DisabilityCenter business;
    
    public NurseWorkAreaJPanel(JPanel bottomPanel, UserAccount userAccount, Organization organization, Enterprise enterprise, DisabilityCenter business) {
        initComponents();
        
        this.bottomPanel = bottomPanel;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.organization = organization;
        this.business = business;
        
        this.lblWelcomeText.setText("Welcome, " + this.userAccount.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcomeText = new javax.swing.JLabel();
        btnDiagnosePatient = new javax.swing.JButton();
        btnCheckInOut = new javax.swing.JButton();

        setBackground(new java.awt.Color(192, 159, 128));

        lblWelcomeText.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        lblWelcomeText.setForeground(new java.awt.Color(118, 50, 63));
        lblWelcomeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeText.setText("Welcome!");

        btnDiagnosePatient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDiagnosePatient.setForeground(new java.awt.Color(118, 50, 63));
        btnDiagnosePatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Nurse/icons8_Heart_Health_32px.png"))); // NOI18N
        btnDiagnosePatient.setText("Diagnose Patients");
        btnDiagnosePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagnosePatientActionPerformed(evt);
            }
        });

        btnCheckInOut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCheckInOut.setForeground(new java.awt.Color(118, 50, 63));
        btnCheckInOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Nurse/icons8_In_Progress_32px.png"))); // NOI18N
        btnCheckInOut.setText("Shift Check-In / Check-Out");
        btnCheckInOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDiagnosePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCheckInOut)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(lblWelcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblWelcomeText)
                .addGap(81, 81, 81)
                .addComponent(btnCheckInOut, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDiagnosePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDiagnosePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnosePatientActionPerformed
        CardLayout layout = (CardLayout)bottomPanel.getLayout();
        bottomPanel.add("PatientQueueJPanel", new PatientQueueJPanel(bottomPanel, userAccount, organization, business));
        layout.next(bottomPanel);
    }//GEN-LAST:event_btnDiagnosePatientActionPerformed

    private void btnCheckInOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInOutActionPerformed
        CardLayout layout = (CardLayout)bottomPanel.getLayout();
        bottomPanel.add("CheckInCheckOutJPanel", new CheckInCheckOutJPanel(bottomPanel, userAccount, organization, business));
        layout.next(bottomPanel);
    }//GEN-LAST:event_btnCheckInOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckInOut;
    private javax.swing.JButton btnDiagnosePatient;
    private javax.swing.JLabel lblWelcomeText;
    // End of variables declaration//GEN-END:variables
}
