/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CEO;



import Business.DisabilityCenter;
import Business.Enterprise.CenterEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author MyPC1
 */
public class CEOWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CEOWorkAreaJPanel
     */
    private JPanel bottomJPanel;
    private DisabilityCenter disabilityCenter;
    public CEOWorkAreaJPanel(JPanel bottomJPanel,  DisabilityCenter disabilityCenter) {
        initComponents();
        this.bottomJPanel = bottomJPanel;
        this.disabilityCenter = disabilityCenter;
        populateTree();
    }
    
    public void populateTree(){
        DefaultTreeModel model=(DefaultTreeModel)DisabilityCenter.getModel();
        ArrayList<Network> networkList=disabilityCenter.getNetworkList();
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Organization> organizationList;
        
        Network network;
        Enterprise enterprise;
        Organization organization;
       // JTree tree = new JTree(new DefaultMutableTreeNode(DisabilityCenter));
        DefaultMutableTreeNode networks=new DefaultMutableTreeNode("Networks");
        DefaultMutableTreeNode root=(DefaultMutableTreeNode)model.getRoot();
        root.setUserObject(disabilityCenter);
        root.removeAllChildren();
        root.insert(networks, 0);
        
        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;
        
        for(int i=0;i<networkList.size();i++){
            network=networkList.get(i);
            networkNode=new DefaultMutableTreeNode(network.getName());
            networks.insert(networkNode, i);
            
            enterpriseList=network.getEnterpriseDirectory().getEnterpriseList();
            for(int j=0; j<enterpriseList.size();j++){
                enterprise=enterpriseList.get(j);
                enterpriseNode=new DefaultMutableTreeNode(enterprise.getName());
                networkNode.insert(enterpriseNode, j);
                if(enterprise instanceof CenterEnterprise){
                    organizationList=enterprise.getOrganizationDirectory().getOrganizationList();
                for(int k=0;k<organizationList.size();k++){
                    organization=organizationList.get(k);
                    organizationNode=new DefaultMutableTreeNode(organization.getName());
                    enterpriseNode.insert(organizationNode, k);
                }
                }
                
            }
        }
        model.reload();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisabilityCenter = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnManageBudget = new javax.swing.JButton();
        btnManageNetwork = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblSelectedNode = new javax.swing.JLabel();

        setBackground(new java.awt.Color(192, 159, 128));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(215, 206, 199));

        DisabilityCenter.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                DisabilityCenterValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(DisabilityCenter);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 348, Short.MAX_VALUE))
        );

        jSplitPane.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(192, 159, 128));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(118, 50, 63));
        jLabel2.setText("CEO Work Area Panel");

        btnManageBudget.setBackground(new java.awt.Color(215, 206, 199));
        btnManageBudget.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageBudget.setForeground(new java.awt.Color(118, 50, 63));
        btnManageBudget.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/CEO/icons8_Money_Bag_32px.png"))); // NOI18N
        btnManageBudget.setText("Manage Network Budget");
        btnManageBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageBudgetActionPerformed(evt);
            }
        });

        btnManageNetwork.setBackground(new java.awt.Color(215, 206, 199));
        btnManageNetwork.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageNetwork.setForeground(new java.awt.Color(118, 50, 63));
        btnManageNetwork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/CEO/icons8_Network_32px_1.png"))); // NOI18N
        btnManageNetwork.setText("Manage Network");
        btnManageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetworkActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel1.setText("Selected Node:");

        lblSelectedNode.setFont(new java.awt.Font("Felix Titling", 1, 30)); // NOI18N
        lblSelectedNode.setText("CEO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(407, 407, 407)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnManageBudget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnManageNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addComponent(lblSelectedNode)))))
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblSelectedNode))
                .addGap(86, 86, 86)
                .addComponent(btnManageNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        jSplitPane.setRightComponent(jPanel2);

        add(jSplitPane, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void DisabilityCenterValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_DisabilityCenterValueChanged
        
        DefaultMutableTreeNode selectedNode= (DefaultMutableTreeNode)DisabilityCenter.getLastSelectedPathComponent();
        if(selectedNode!=null){
            lblSelectedNode.setText(selectedNode.toString());
        }
    }//GEN-LAST:event_DisabilityCenterValueChanged

    private void btnManageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetworkActionPerformed
        java.util.logging.Logger.getLogger(CEOWorkAreaJPanel.class.getName()).log(java.util.logging.Level.INFO, "Going to Manage Network Panel!");
        ManageNetworkJPanel manageNetworkJPanel=new ManageNetworkJPanel(bottomJPanel, disabilityCenter);
        bottomJPanel.add("manageNetworkJPanel",manageNetworkJPanel);
        CardLayout layout=(CardLayout)bottomJPanel.getLayout();
        layout.next(bottomJPanel);
    }//GEN-LAST:event_btnManageNetworkActionPerformed

    private void btnManageBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBudgetActionPerformed
        java.util.logging.Logger.getLogger(CEOWorkAreaJPanel.class.getName()).log(java.util.logging.Level.INFO, "Going to Manage Budget Panel!");
        NetworkBudgetJPanel networkBudgetJPanel=new NetworkBudgetJPanel(bottomJPanel, disabilityCenter);
        bottomJPanel.add("NetworkBudgetJPanel",networkBudgetJPanel);
        CardLayout layout=(CardLayout)bottomJPanel.getLayout();
        layout.next(bottomJPanel);
    }//GEN-LAST:event_btnManageBudgetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree DisabilityCenter;
    private javax.swing.JButton btnManageBudget;
    private javax.swing.JButton btnManageNetwork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JLabel lblSelectedNode;
    // End of variables declaration//GEN-END:variables
}
