/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CEO;

import Business.DB4OUtil.DB4OUtil;
import Business.DisabilityCenter;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ManageNetworkJPanel extends javax.swing.JPanel {

    

    /**
     *
     * Creates new form ManageNetworkJPanel
     */
    private JPanel bottomJPanel;
    private DisabilityCenter disabilityCenter;
    public ManageNetworkJPanel(JPanel bottomJPanel,DisabilityCenter disabilityCenter) {
        initComponents();

        this.bottomJPanel = bottomJPanel;
        this.disabilityCenter = disabilityCenter;
        
        populateNetworkTable();
    }

    private void populateNetworkTable() {
        DefaultTableModel model = (DefaultTableModel) networkJTable.getModel();

        model.setRowCount(0);
        for (Network network : disabilityCenter.getNetworkList()) {
            Object[] row = new Object[model.getColumnCount()];
            row[0] = network.getName();
            row[1] = network.getEmployeeDirectory().getEmployeeList().get(0).getName();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        networkJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        submitJButton = new javax.swing.JButton();
        txtFieldNetwork = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        txtFieldRegionalManager = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFieldPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txtFieldName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(192, 159, 128));

        networkJTable.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        networkJTable.setForeground(new java.awt.Color(118, 50, 63));
        networkJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Regional Manger"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(networkJTable);
        if (networkJTable.getColumnModel().getColumnCount() > 0) {
            networkJTable.getColumnModel().getColumn(0).setResizable(false);
            networkJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(118, 50, 63));
        jLabel1.setText("Network Name*");

        submitJButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(118, 50, 63));
        submitJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/CEO/icons8_Submit_Progress_32px.png"))); // NOI18N
        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        txtFieldNetwork.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtFieldNetwork.setForeground(new java.awt.Color(86, 86, 86));

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backJButton.setForeground(new java.awt.Color(118, 50, 63));
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/CEO/icons8_Back_To_32px_1.png"))); // NOI18N
        backJButton.setText(" Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        txtFieldRegionalManager.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtFieldRegionalManager.setForeground(new java.awt.Color(86, 86, 86));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(118, 50, 63));
        jLabel2.setText("Regional Manager Name*");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(118, 50, 63));
        jLabel4.setText("Password*");

        txtFieldPassword.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtFieldPassword.setForeground(new java.awt.Color(86, 86, 86));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(118, 50, 63));
        jLabel5.setText("Username*");

        txtFieldName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtFieldName.setForeground(new java.awt.Color(86, 86, 86));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(118, 50, 63));
        jLabel3.setText("Manage network");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtFieldName)
                                    .addComponent(txtFieldRegionalManager, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFieldPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFieldNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(submitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton)))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFieldRegionalManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(submitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backJButton)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        String name = txtFieldNetwork.getText();
        String regionalManager = txtFieldRegionalManager.getText();
        String username = txtFieldName.getText();
        String password = String.valueOf(txtFieldPassword.getPassword());
        
        if ( txtFieldNetwork.getText().isEmpty()) {
            java.util.logging.Logger.getLogger(ManageNetworkJPanel.class.getName()).log(java.util.logging.Level.INFO, "Name of network is Empty!");
            JOptionPane.showMessageDialog(null, "Please enter the name of the network");
            txtFieldNetwork.setText("");          
            return;
        }
        
        if(txtFieldRegionalManager.getText().isEmpty()){
            java.util.logging.Logger.getLogger(ManageNetworkJPanel.class.getName()).log(java.util.logging.Level.INFO, "Name of Regional Manager is Empty!");
            JOptionPane.showMessageDialog(null, "Please enter Regional Manager");
            return;
        }
        if(txtFieldName.getText().length() < 5 || txtFieldPassword.getText().length() < 5){
            java.util.logging.Logger.getLogger(ManageNetworkJPanel.class.getName()).log(java.util.logging.Level.INFO, "Username or Password entered is not valid! username: "+txtFieldName.getText()+" password: "+txtFieldPassword.getPassword());
            JOptionPane.showMessageDialog(null, "Please enter username and password with length more than 5 characters");
            return;
        }
        
        for(Network network :disabilityCenter.getNetworkList())
        if(network.getName().equals(name)){
            java.util.logging.Logger.getLogger(ManageNetworkJPanel.class.getName()).log(java.util.logging.Level.INFO, "Network "+txtFieldNetwork.getText()+" already exists!");
           JOptionPane.showMessageDialog(null, "Network with this location already exists");
           txtFieldNetwork.setText("");
            return; 
        }
        Network network = disabilityCenter.createAndAddNetwork();
        network.setName(name);
        UserAccount ua = network.addRegionalManager(username, password, regionalManager);
        if(ua == null){
            //error occured while adding regional manager
            disabilityCenter.removeNetwork(network);
            return;
        }
        java.util.logging.Logger.getLogger(ManageNetworkJPanel.class.getName()).log(java.util.logging.Level.INFO, "Network "+txtFieldNetwork.getText()+" created successfully! Regional Manager "+txtFieldRegionalManager.getText()+" appointed!");
        JOptionPane.showMessageDialog(null, "Network has been created and regional manager has been appointed!! ");
        
        populateNetworkTable();
        DB4OUtil.getInstance().storeSystem(disabilityCenter);
        
        txtFieldNetwork.setText("");
        txtFieldRegionalManager.setText("");
        txtFieldName.setText("");
        txtFieldPassword.setText("");
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        bottomJPanel.remove(this);
        Component[] componentArray = bottomJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CEOWorkAreaJPanel cEOWorkAreaJPanel = (CEOWorkAreaJPanel) component;
        cEOWorkAreaJPanel.populateTree();
        CardLayout layout = (CardLayout) bottomJPanel.getLayout();
        layout.previous(bottomJPanel);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable networkJTable;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField txtFieldName;
    private javax.swing.JTextField txtFieldNetwork;
    private javax.swing.JPasswordField txtFieldPassword;
    private javax.swing.JTextField txtFieldRegionalManager;
    // End of variables declaration//GEN-END:variables
}
