/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CEO;

import Business.DisabilityCenter;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cardinal
 */
public class NetworkBudgetJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CenterBudgetJPanel
     */
    private JPanel bottomJPanel;
    private DisabilityCenter disabilityCenter;

    public NetworkBudgetJPanel(JPanel bottomJPanel, DisabilityCenter disabilityCenter) {
        initComponents();
        this.bottomJPanel = bottomJPanel;
        this.disabilityCenter = disabilityCenter;
        populateNetworkComboBox();
        populateNetworkTable();
    }

    public void populateNetworkComboBox() {
        networkJComboBox.removeAllItems();
        for (Network network : disabilityCenter.getNetworkList()) {
            networkJComboBox.addItem(network);
        }
    }

    private void populateNetworkTable() {
        DefaultTableModel model = (DefaultTableModel) budgetJTable.getModel();
        model.setRowCount(0);
        //if(!organization.getEmployeeDirectory().getEmployeeList().contains(centerHead))
        for (Network network : disabilityCenter.getNetworkList()) {
            {
                Object[] row = new Object[2];
                row[0] = network.getName();
                row[1] = network.getBudget();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<String>();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        budgetJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        txtFieldBudget = new javax.swing.JTextField();
        btnSetBudget = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBackground(new java.awt.Color(192, 159, 128));

        budgetJTable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        budgetJTable.setForeground(new java.awt.Color(118, 50, 63));
        budgetJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Network", "Budget"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(budgetJTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(118, 50, 63));
        jLabel1.setText("Select Network:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(118, 50, 63));
        jLabel2.setText("Set Budget:");

        networkJComboBox.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        networkJComboBox.setForeground(new java.awt.Color(118, 50, 63));
        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });

        txtFieldBudget.setForeground(new java.awt.Color(118, 50, 63));

        btnSetBudget.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnSetBudget.setForeground(new java.awt.Color(118, 50, 63));
        btnSetBudget.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/CEO/icons8_Submit_Progress_32px.png"))); // NOI18N
        btnSetBudget.setText("Set Budget");
        btnSetBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetBudgetActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(118, 50, 63));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/CEO/icons8_Back_To_32px_1.png"))); // NOI18N
        btnBack.setText(" Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(118, 50, 63));
        jLabel3.setText("Manage network Budget");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(networkJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFieldBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(418, 418, 418)
                        .addComponent(btnSetBudget))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(76, 76, 76)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(networkJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFieldBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnSetBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnBack)
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetBudgetActionPerformed
        Network network = (Network) networkJComboBox.getSelectedItem();
        //String name = txtFieldBudget.getText();
        double budget = 0.0;
        double networkBudget = 0.0;
        if (txtFieldBudget.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a budget");
            java.util.logging.Logger.getLogger(NetworkBudgetJPanel.class.getName()).log(java.util.logging.Level.INFO, "Budget field is blank!");
            txtFieldBudget.setText("");
            return;
        }
        try {
            budget = Double.parseDouble(txtFieldBudget.getText());
            if (budget <= 0) {
                JOptionPane.showMessageDialog(null, "Value needs to be greater than 0");
                java.util.logging.Logger.getLogger(NetworkBudgetJPanel.class.getName()).log(java.util.logging.Level.INFO, "Budget needs  to be greater than 0!");
                return;
            }
            networkBudget = network.getBudget();
//            network.setBudget(budget + networkBudget);
//            txtFieldBudget.setText("");
//            JOptionPane.showMessageDialog(null, "Network Budget has been set.");

            Double.parseDouble(txtFieldBudget.getText());
        } catch (NumberFormatException e) {
            java.util.logging.Logger.getLogger(NetworkBudgetJPanel.class.getName()).log(java.util.logging.Level.INFO, "Budget needs to be numeric! Entered value: "+txtFieldBudget.getText());
            JOptionPane.showMessageDialog(this, "Please add numeric field for Budget");
            txtFieldBudget.setText("");
            return;
        }
        network.setBudget(budget + networkBudget);
        populateNetworkTable();
        JOptionPane.showMessageDialog(this, "Budget has been set.");
        java.util.logging.Logger.getLogger(NetworkBudgetJPanel.class.getName()).log(java.util.logging.Level.INFO, "Budget "+txtFieldBudget.getText()+" has been set successfully for Network "+network.getName());
        txtFieldBudget.setText("");

    }//GEN-LAST:event_btnSetBudgetActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        bottomJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) bottomJPanel.getLayout();
        cardLayout.previous(bottomJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_networkJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSetBudget;
    private javax.swing.JTable budgetJTable;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JTextField txtFieldBudget;
    // End of variables declaration//GEN-END:variables
}
