/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CenterHead;

import Business.Enterprise.Enterprise;
import Business.Enterprise.CenterEnterprise;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author cardinal
 */

public class CenterHeadWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CenterHeadWorkAreaJPanel
     */
    private JPanel bottomPanel;
    private Enterprise enterprise;
    private Organization organization;
    private UserAccount account;
    
    public CenterHeadWorkAreaJPanel(JPanel bottomPanel, UserAccount account, Organization organization, Enterprise enterprise) {
        initComponents();
        this.bottomPanel = bottomPanel;
        this.enterprise = enterprise;
        this.organization = organization;
        this.account = account;
        CenterEnterprise centerEnterprise = (CenterEnterprise) enterprise;
        valueLabel.setText(centerEnterprise.getCenterHead().getName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        btnManageUser = new javax.swing.JButton();
        manageEmployeeJButton = new javax.swing.JButton();
        btnManageOrganization = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(192, 159, 128));

        enterpriseLabel.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        enterpriseLabel.setText("CenterHead :");

        valueLabel.setFont(new java.awt.Font("Felix Titling", 1, 30)); // NOI18N
        valueLabel.setText("<value>");

        btnManageUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageUser.setForeground(new java.awt.Color(118, 50, 63));
        btnManageUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/CenterHead/icons8_Management_32px.png"))); // NOI18N
        btnManageUser.setText("Manage User");
        btnManageUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUserActionPerformed(evt);
            }
        });

        manageEmployeeJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageEmployeeJButton.setForeground(new java.awt.Color(118, 50, 63));
        manageEmployeeJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/CenterHead/icons8_Add_User_Male_32px.png"))); // NOI18N
        manageEmployeeJButton.setText("Manage Employee");
        manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButtonActionPerformed(evt);
            }
        });

        btnManageOrganization.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageOrganization.setForeground(new java.awt.Color(118, 50, 63));
        btnManageOrganization.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/CenterHead/icons8_Organization_32px.png"))); // NOI18N
        btnManageOrganization.setText("Manage Organization");
        btnManageOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrganizationActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(118, 50, 63));
        jLabel5.setText("Center Head Role Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(valueLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(manageEmployeeJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageOrganization, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel))
                .addGap(48, 48, 48)
                .addComponent(btnManageOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageEmployeeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUserActionPerformed
        ManageUserAccountJPanel manageUserAccountJPanel = new ManageUserAccountJPanel(bottomPanel, enterprise);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        bottomPanel.add("ManageUserAccountJPanel", manageUserAccountJPanel);
        layout.next(bottomPanel);
       
    }//GEN-LAST:event_btnManageUserActionPerformed

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed
        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(bottomPanel, enterprise.getOrganizationDirectory(), organization, enterprise);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        bottomPanel.add("ManageEmployeeJPanel", manageEmployeeJPanel);
        layout.next(bottomPanel);
        
    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed

    private void btnManageOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrganizationActionPerformed
        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(bottomPanel, enterprise.getOrganizationDirectory());
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        bottomPanel.add("ManageEmployeeJPanel", manageOrganizationJPanel);
        layout.next(bottomPanel);
    }//GEN-LAST:event_btnManageOrganizationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageOrganization;
    private javax.swing.JButton btnManageUser;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton manageEmployeeJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
