/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Supplier;

import Business.DisabilityCenter;
import Business.Enterprise.Enterprise;
import Business.Organization.Supplier;
import Business.Organization.SupplierProduct.Product;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author cardinal
 */
public class ViewBestFiveProductsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewBestFiveProductsJPanel
     */
    private JPanel bottomPanel;
    private Supplier supplier;
    private Map<Product, Double> productList;
    private Map<Product, Double> newList;
    private List<Map.Entry<Product, Double>> bestFive;

    public ViewBestFiveProductsJPanel(JPanel bottomPanel, Supplier supplier) {
        initComponents();
        this.bottomPanel = bottomPanel;
        this.supplier = supplier;
        productList = new HashMap<Product, Double>();
        newList = new HashMap<Product, Double>();
        bestFive = new ArrayList<Map.Entry<Product, Double>>();
        BestFiveProducts();

    }

    private void BestFiveProducts() {

        for (Product product : supplier.getProductCatalog().getProductList()) {
            double revenue = (product.getOriginalQuantity() - product.getQuantity()) * product.getPrice();
            productList.put(product, revenue);

            //convert userPostCount map to a list
            bestFive = new ArrayList<Map.Entry<Product, Double>>(productList.entrySet());

            //sort the list in ascending order of number of posts
            Collections.sort(bestFive, new Comparator<Map.Entry<Product, Double>>() {
                @Override
                public int compare(Map.Entry<Product, Double> o1, Map.Entry<Product, Double> o2) {
                    return (int) (o2.getValue() - o1.getValue());
                }

            });

            for (int i = 0; i < bestFive.size() && i < 5; i++) {
                newList.put(bestFive.get(i).getKey(), bestFive.get(i).getValue());
            }
            this.showChart();
        }
    }

    private void showChart() {
        DefaultCategoryDataset dcd = new DefaultCategoryDataset();
        for (int i = 0; i < bestFive.size() && i < 5; i++) {
            Product productName = (Product) (bestFive.get(i).getKey());
            double productQuantity = (double) (bestFive.get(i).getValue());
            dcd.setValue(productQuantity, "Sales", productName.getName());
        }
        JFreeChart jFreeChart = ChartFactory.createBarChart3D("Sales Report", "Product Name", "Revenue", dcd, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot plot = jFreeChart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.black);
        ChartPanel chartPanel = new ChartPanel(jFreeChart);
        barchartPanel.removeAll();
        barchartPanel.add(chartPanel);
        barchartPanel.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barchartPanel = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(192, 159, 128));

        barchartPanel.setBackground(new java.awt.Color(204, 214, 223));
        barchartPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        barchartPanel.setLayout(new javax.swing.BoxLayout(barchartPanel, javax.swing.BoxLayout.LINE_AXIS));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(118, 50, 63));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Supplier/icons8_Back_To_32px_1.png"))); // NOI18N
        btnBack.setText(" Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(barchartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barchartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        bottomPanel.remove(this);
        CardLayout cardLayout = (CardLayout) bottomPanel.getLayout();
        cardLayout.previous(bottomPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barchartPanel;
    private javax.swing.JButton btnBack;
    // End of variables declaration//GEN-END:variables
}
