/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.InventoryManager;

import Business.DisabilityCenter;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author cardinal
 */
public class InventoryManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InventoryManagerWorkAreaJPanel
     */
    private JPanel bottomPanel;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Organization organization;
    private DisabilityCenter business;
    private Network network;
    
    public InventoryManagerWorkAreaJPanel(JPanel bottomPanel, UserAccount account, Organization organization, Enterprise enterprise,DisabilityCenter business) {
        initComponents();
        this.bottomPanel = bottomPanel;
        this.userAccount = account;
        this.enterprise = enterprise;
        this.organization = organization;
        this.business = business;
        this.network = null;
        valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        btnPlaceOrder = new javax.swing.JButton();
        btnProvideEquipmentMedicines = new javax.swing.JButton();
        btnViewProductCatalog = new javax.swing.JButton();
        lblWelcomeText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(192, 159, 128));

        enterpriseLabel.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        enterpriseLabel.setText("Inventory Manager");

        valueLabel.setFont(new java.awt.Font("Felix Titling", 1, 30)); // NOI18N
        valueLabel.setText("<value>");

        btnPlaceOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPlaceOrder.setForeground(new java.awt.Color(118, 50, 63));
        btnPlaceOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/InventoryManager/icons8_Buying_32px.png"))); // NOI18N
        btnPlaceOrder.setText("Place order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        btnProvideEquipmentMedicines.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnProvideEquipmentMedicines.setForeground(new java.awt.Color(118, 50, 63));
        btnProvideEquipmentMedicines.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/InventoryManager/icons8_Pill_32px.png"))); // NOI18N
        btnProvideEquipmentMedicines.setText("Provide Equipment/medicines");
        btnProvideEquipmentMedicines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProvideEquipmentMedicinesActionPerformed(evt);
            }
        });

        btnViewProductCatalog.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewProductCatalog.setForeground(new java.awt.Color(118, 50, 63));
        btnViewProductCatalog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/InventoryManager/icons8_Product_32px.png"))); // NOI18N
        btnViewProductCatalog.setText("View Inventory Catalog");
        btnViewProductCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProductCatalogActionPerformed(evt);
            }
        });

        lblWelcomeText.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        lblWelcomeText.setForeground(new java.awt.Color(118, 50, 63));
        lblWelcomeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeText.setText("Inventory Manager Role Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(lblWelcomeText))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnPlaceOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnProvideEquipmentMedicines, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnViewProductCatalog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcomeText)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel))
                .addGap(80, 80, 80)
                .addComponent(btnProvideEquipmentMedicines, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnViewProductCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProvideEquipmentMedicinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProvideEquipmentMedicinesActionPerformed
        ProvideEquipmentMedicinesJPanel provideEquipmentMedicinesJPanel = new ProvideEquipmentMedicinesJPanel(bottomPanel, organization,business);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        bottomPanel.add("ProvideEquipmentMedicinesJPanel", provideEquipmentMedicinesJPanel);
        layout.next(bottomPanel);
    }//GEN-LAST:event_btnProvideEquipmentMedicinesActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        for(Network n : business.getNetworkList()){
            if(n.getEnterpriseDirectory().getEnterpriseList().contains(enterprise)){
                this.network = n;
            }
        }
        PlaceOrderJPanel placeOrderJPanel = new PlaceOrderJPanel(bottomPanel,network, enterprise);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        bottomPanel.add("PlaceOrderJPanel", placeOrderJPanel);
        layout.next(bottomPanel);
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnViewProductCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProductCatalogActionPerformed
        ViewInventoryListJPanel viewProductCatalogJPanel = new ViewInventoryListJPanel(bottomPanel, organization);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        bottomPanel.add("ViewProductCatalogJPanel", viewProductCatalogJPanel);
        layout.next(bottomPanel);
    }//GEN-LAST:event_btnViewProductCatalogActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnProvideEquipmentMedicines;
    private javax.swing.JButton btnViewProductCatalog;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel lblWelcomeText;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
