/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Common;

import Business.DisabilityCenter;
import Business.Organization.Organization;
import Business.Organization.Patient;;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cardinal
 */
public class PatientQueueJPanel extends javax.swing.JPanel {

    private JPanel bottomPanel;
    private UserAccount userAccount;
    private Organization organization;
    private DisabilityCenter business;

    /**
     * Creates new form DiagnosePatientJPanel
     */
    public PatientQueueJPanel(JPanel bottomPanel, UserAccount userAccount, Organization organization, DisabilityCenter business) {
        initComponents();

        this.bottomPanel = bottomPanel;
        this.userAccount = userAccount;
        this.organization = organization;
        this.business = business;
        
        refreshQueue();
    }

    public void refreshQueue() {
        DefaultTableModel model = (DefaultTableModel) patientQueueJTable.getModel();

        model.setRowCount(0);
        for (WorkRequest w : userAccount.getWorkQueue().getWorkRequestList()) {
            Patient p = (Patient) w.getObject();
            Object row[] = new Object[2];
            row[0] = p.getPatientID();
            row[1] = p;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientQueueJTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnDiagnosePatient = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(118, 50, 63));
        jLabel5.setText("Patient Diagnosis");

        setBackground(new java.awt.Color(192, 159, 128));

        patientQueueJTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        patientQueueJTable.setForeground(new java.awt.Color(118, 50, 63));
        patientQueueJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "Patient Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(patientQueueJTable);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(118, 50, 63));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Common/icons8_Back_To_32px_1.png"))); // NOI18N
        btnBack.setText(" Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDiagnosePatient.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnDiagnosePatient.setForeground(new java.awt.Color(118, 50, 63));
        btnDiagnosePatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Common/icons8_Heart_Health_32px.png"))); // NOI18N
        btnDiagnosePatient.setText("Diagnose >>");
        btnDiagnosePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagnosePatientActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(118, 50, 63));
        jLabel2.setText("Patient Queue:");

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(118, 50, 63));
        jLabel6.setText("Diagnose Patient");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(jLabel2)
                                .addGap(356, 356, 356))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnDiagnosePatient)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(228, 228, 228)
                            .addComponent(jLabel6))))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnDiagnosePatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        bottomPanel.remove(this);       
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        layout.previous(bottomPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDiagnosePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnosePatientActionPerformed
        int row = patientQueueJTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please make a selection!!");
            return;
        }
        Patient patient = (Patient)patientQueueJTable.getValueAt(row, 1);
        DiagnosePatientJPanel diagnosePatientJPanel = new DiagnosePatientJPanel(bottomPanel, userAccount, organization, patient, business, null);
        CardLayout cardLayout = (CardLayout) bottomPanel.getLayout();
        bottomPanel.add(diagnosePatientJPanel);
        cardLayout.next(bottomPanel);
    }//GEN-LAST:event_btnDiagnosePatientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDiagnosePatient;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable patientQueueJTable;
    // End of variables declaration//GEN-END:variables
}
